-- local buf = vim.api.nvim_create_buf(true, false)
--
-- vim.api.nvim_set_current_buf(buf)
-- vim.api.nvim_chan_send(vim.bo[buf].channel, "zsh\n")
--
-- vim.cmd("vs")
-- vim.api.nvim_set_current_buf(buf)
